## NUMPY
### Arrays
* Son mejores que las listas porque ocupan menos espacios
* Ayudan  ahacer operaciones sin iterar

In [ ]:
#importanto las librerias
import numpy as np

In [ ]:
# Creando arreglo a partir de una objeto iterable
lista = [10, 20, 30, 40, 50, 60]
type(lista)

list

In [ ]:
#Creando array
a = np.array(lista)
type(a)

numpy.ndarray

#### Atributos de Array:
* ndim :  cantidad de dimensiones que tiene el arreglo
* size : elementos que posee el arreglo
* itemsize : conocer el tamaño en bite de cada elmento en el arreglo
* shape : conocer la forma del arreglo

In [ ]:
print("usando ndim", a.ndim)
print("usando size", a.size)
print("usando itemsize", a.itemsize)
print("usando shape", a.shape)


usando ndim 1
usando size 6
usando itemsize 8
usando shape (6,)


#### Obteniendo elementos del arreglo

In [ ]:
print("primer elemento", a[0])
print("ultimo elemento", a[a.size -1])
print("ultimo elemento", a[-1])
print("del 1 al 3", a[0:3])
print("invierto", a[::-1])

primer elemento 10
ultimo elemento 60
ultimo elemento 60
del 1 al 3 [10 20 30]
invierto [60 50 40 30 20 10]


#### Operaciones Sobre los arreglos

In [ ]:
#Usando Indices
lista_indice = [0,3,4,5]
print("lista", a[lista_indice]) #me va generar los elementos del array que tienen eso indices
print("lista directo", a[[0,3,4,5]])#Tambien se puede colocar la lista directamente en el array
print("haciendo operaciones en el array", ((a*10)-5)/2)

lista [10 40 50 60]
lista directo [10 40 50 60]
haciendo operaciones en el array [ 47.5  97.5 147.5 197.5 247.5 297.5]


### Tipos de Datos en NP

Tipo	Caracter

* Bool	**?**
* byte (Signed)	**b**
* byte (unsigned)	**B**
* integer (Signed)	**i**
* integer (unsigned)	**u**
* float	**f**
* complex	**c**
* timedelta	**m**
* datetime	**M**
* Objects	**O**
* Unicode	**U**

In [ ]:
np.array([1,2,3,4,5]) #un arreglo de numeros enteros
np.array([1,2,3,4,5], dtype = "f") #arreglo de flotantes
np.array([1,2,3,4,5], dtype = np.float32) #arreglo de flotantes

array([1., 2., 3., 4., 5.], dtype=float32)

### Creacion de arreglos
* np.arange(donde_empieza, donde_termina) el ultimop elemento no se toma en cuenta
* np.arange(donde_empieza, donde_termina, saltos)
* np.zeros(nro_elemtos, dtype) genera arreglo de ceros
* np.full(nro_elementos, numero)
* np.random.random(nro_elementos) random sin rango
* np.random.randint(inicio, fin, nro_elementos)

In [ ]:
#Funciones utiles para arreglos
print("con saltos", np.arange(0,15,3))
print("cero", np.zeros(10, dtype = "i"))
print("unos", np.ones(10))
print("escogiendo el numero", np.full(10,5))
print("random sin rango", np.random.random(5))
print("random con rango", np.random.randint(1,100,5))

con saltos [ 0  3  6  9 12]
cero [0 0 0 0 0 0 0 0 0 0]
unos [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
escogiendo el numero [5 5 5 5 5 5 5 5 5 5]
random sin rango [0.00177679 0.0856373  0.93138697 0.29368044 0.6945557 ]
random con rango [18 97 20 81 80]


### Matrices
tiene como argumento una lista que a su vez almacenará otras listas

In [ ]:
mimatriz = np.array([
          [1,2,3,4,5],
          [10,20,30,40,50],
          [100,200,300,400,500]
])
print(mimatriz)
print("nro dimensiones", mimatriz.ndim)
print("forma de matriz", mimatriz.shape)
print("nro elementos", mimatriz.size)
print("primer elemento", mimatriz[0][0])
print("segunda fila 4to elmento", mimatriz[1,3])
print("segunda fila hasta el 4to elemento", mimatriz[1,0:3])
print("arreglo de una sola dimension", mimatriz.ravel())

[[  1   2   3   4   5]
 [ 10  20  30  40  50]
 [100 200 300 400 500]]
nro dimensiones 2
forma de matriz (3, 5)
nro elementos 15
primer elemento 1
segunda fila 4to elmento 40
segunda fila hasta el 4to elemento [10 20 30]
arreglo de una sola dimension [  1   2   3   4   5  10  20  30  40  50 100 200 300 400 500]


#### Actualizando arreglos

In [ ]:
a =  np.arange(0,15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
#cambio elemnto 5
a[5]=100
a

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [ ]:
#Cambio cambio varios elemntos de 0 a 3
a[1:4] = 5
a

array([  0,   5,   5,   5,   4, 100,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [ ]:
#cambio elementos varios no seguidos
a[[6,8]] = 1000
a

array([   0,    5,    5,    5,    4,  100, 1000,    7, 1000,    9,   10,
         11,   12,   13,   14])

In [ ]:
#aumentar arreglo a la ultima parte
a_mas_uno = np.append(a,[50,100, 150])
#quitar arreglo desde la poscione
a_menos_uno = np.delete(a,[[0,14]])

print(a_mas_uno)
print(a_menos_uno)

[   0    5    5    5    4  100 1000    7 1000    9   10   11   12   13
   14   50  100  150]
[   5    5    5    4  100 1000    7 1000    9   10   11   12   13]


In [ ]:
#cambiar al array a una matriz
a.shape = (3,5)
a

array([[   0,    5,    5,    5,    4],
       [ 100, 1000,    7, 1000,    9],
       [  10,   11,   12,   13,   14]])

In [ ]:
#regresar la matriz a array
a.shape = (a.size,)
a

array([   0,    5,    5,    5,    4,  100, 1000,    7, 1000,    9,   10,
         11,   12,   13,   14])

### Transposicion

### Creando una matriz


In [ ]:
#Creo un matriz
a = np.arange(0,10).reshape (2,5)
a
          

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
#traspongo la matriz creada
print(a.T)
print(a.transpose)

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
<built-in method transpose of numpy.ndarray object at 0x7f497222a440>


In [ ]:
#Operaciones con array
a = np.arange(1,11)
print("suma todos los elementos", a.sum())
print("elemento max", a.max())
print("desvest del arreglo", a.std())
print("media del arreglo", a.mean())


suma todos los elementos 55
elemento max 10
desvest del arreglo 2.8722813232690143
media del arreglo 5.5


In [ ]:
#operaciones con matriz 
m = np.random.randint(1,11,50)
m

None


In [ ]:
m.sort()
m #ordena de menor a mayor


array([ 1,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6,  7,  7,  7,  7,  7,  7,
        7,  7,  7,  8,  8,  8,  8,  9,  9,  9,  9,  9, 10, 10, 10, 10])

### Ejecucion de Funciones

In [ ]:
a= np.random.randint(1,10,10)
a



array([1, 2, 9, 4, 7, 1, 7, 4, 9, 6])

In [ ]:
def operacion_simple (val):
  return val *10


print(operacion_simple(a[0])) #muñtiplicar un elemento del array


10


In [ ]:

for i in a: 
  print(operacion_simple(i)) #multiplicar todos los elemntos

10
20
90
40
70
10
70
40
90
60


In [ ]:
#Aplicar lafuncion dirrectamente sobre el arreglo
#VECTORIZANDO LA FUNCION
funcion_vectorizada= np.vectorize(operacion_simple)

#aplicarle al arreglo sin for
print(funcion_vectorizada(a))

[10 20 90 40 70 10 70 40 90 60]


### Copias y vistas

In [ ]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#creo una copia de a, cada cambio que la haga a b se vera reflejado en a
b=a

In [ ]:
a is b

True

### Operadores relacionales y logicos

In [ ]:
a = np.random.randint(1,10,50)
print(a<5)

[False  True  True False False  True False  True  True False False  True
  True False  True  True False False False False  True False  True False
  True False  True False  True  True False False  True  True  True False
  True False False False False  True  True False False False  True False
 False False]


In [ ]:
# obtengo todos los true de mis array
a[a<5]

array([2, 1, 2, 4, 4, 1, 3, 4, 1, 3, 3, 4, 3, 2, 2, 3, 2, 2, 3, 3, 2, 3])

In [ ]:
# obtengo todos los true de mis array AND
a[(a<5) & (a>2) & (a==9)]

array([], dtype=int64)

In [ ]:
# obtengo todos los true de mis array OR
a[(a<5) | (a>2) | (a==9)]

array([5, 2, 1, 5, 8, 2, 9, 4, 4, 6, 6, 1, 3, 5, 4, 1, 7, 8, 7, 6, 3, 5,
       3, 6, 4, 5, 3, 6, 2, 2, 5, 8, 3, 2, 2, 5, 3, 6, 9, 6, 8, 3, 2, 8,
       7, 5, 3, 5, 9, 7])

In [ ]:
# obtengo todos los true de mis array DIFERENTE
a[ (a!=2) & (a!=9)]

array([5, 1, 5, 8, 4, 4, 6, 6, 1, 3, 5, 4, 1, 7, 8, 7, 6, 3, 5, 3, 6, 4,
       5, 3, 6, 5, 8, 3, 5, 3, 6, 6, 8, 3, 8, 7, 5, 3, 5, 7])

### Comparando arreglos

In [ ]:
a = np.random.randint(1,5,10)
b = np.random.randint(1,5,10)

In [ ]:
print(a == b)
print(a < b)

[False False False False False False False False False False]
[ True False  True  True  True False False  True  True False]


In [ ]:
a[(a<b)]

array([3, 1, 2, 2, 1, 1])

### Guardando  y leyendo archivos
Si se trabaja con muchos datos e smejor guardarlos en archivos binarios comprimidos
* para eso usamos **np.savez**

In [ ]:
a= np.arange(30)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
#guardnao el archivo
np.savetxt("un_array.txt", a)
np.savetxt("un_array.csv", a, delimiter =";" )
np.save("un_array.npy", a ) #creando un archivo binario

In [ ]:
#abro archivo
b = np.loadtxt("/content/sample_data/mnist_test.csv", delimiter=",")

In [ ]:
carga = np.load('/content/un_array.npy')
carga

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

## PANDAS
Serie: arreglo de una sola dimension

In [ ]:
import pandas as pd

In [ ]:
pd.Series([10,20, 30, 40, 50], dtype = "f") 
# creo una serie y le puedo poner el type que quiero

0    10.0
1    20.0
2    30.0
3    40.0
4    50.0
dtype: float32

In [ ]:
#cambiando indice
a = pd.Series([10,20, 30, 40, 50], dtype = "f", index= ['a','b','c','d','e']) 
print(a)

a    10.0
b    20.0
c    30.0
d    40.0
e    50.0
dtype: float32


In [ ]:
#puedo ingresar al elemento segun el index u orden
print(a[0])
print(a['a'])

10.0
10.0


#### Serie s apartir de diccionarios

In [ ]:
diccionario = {'a':10 , "b":20, 'c':30} 
#Creo el diccionario

In [ ]:
c = pd.Series(diccionario)
c

a    10
b    20
c    30
dtype: int64

#### Serie con arange

In [ ]:
a = pd.Series(np.arange(15), dtype='i')
a

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
dtype: int32

In [ ]:
#coloandoles nombre a la serie y a los indexz
a.name = 'numeros de ana'
a.index.name = 'indices'
a

indices
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
Name: numeros de ana, dtype: int32

### NaN
np.NaN

In [ ]:
#Creo un serie con NaN
a = pd.Series([10, 20, np.NaN, 40 , np.NaN])
a

0    10.0
1    20.0
2     NaN
3    40.0
4     NaN
dtype: float64

In [ ]:
#encontrando nulos
print( pd.isnull(a) ) #nuestra elementos que no posee valor
print(pd.notnull(a)) #esta es la evez muestra los si tiene NaN
print(pd.isnull(a))

0    False
1    False
2     True
3    False
4     True
dtype: bool
0     True
1     True
2    False
3     True
4    False
dtype: bool
0    False
1    False
2     True
3    False
4     True
dtype: bool


In [ ]:
#elimino NaN , no altera laserie original
b = a.dropna()
b

0    10.0
1    20.0
3    40.0
dtype: float64

In [ ]:
#si quiero colocar valores en los null, los reemplazo con mean
c = a.fillna(a.mean())
c

0    10.000000
1    20.000000
2    23.333333
3    40.000000
4    23.333333
dtype: float64

### Dataframe
pd.DataFrame()

In [ ]:
#Voy creando in diccionario 
usuarios = {
    "nombre":['ana','maria','flor', 'fanna'],
    'notas': [10,15,17,16],
    'edad': [14,16,15,14],
    'apobado':[True,True, False, True]
}

In [ ]:
#creando dataframe
a = pd.DataFrame(usuarios)
a

nombre  notas  edad  apobado
0    ana     10    14     True
1  maria     15    16     True
2   flor     17    15    False
3  fanna     16    14     True

In [ ]:
print(a.nombre)
print(a['nombre'])

0      ana
1    maria
2     flor
3    fanna
Name: nombre, dtype: object
0      ana
1    maria
2     flor
3    fanna
Name: nombre, dtype: object


In [ ]:
#obteniendo nombre de columnas
print(a.columns)
print(a.index)
print(a.values) #rreglo de dos dim

Index(['nombre', 'notas', 'edad', 'apobado'], dtype='object')
RangeIndex(start=0, stop=4, step=1)
[['ana' 10 14 True]
 ['maria' 1 16 True]
 ['flor' 17 15 False]
 ['fanna' 16 14 True]]


In [ ]:
#usando solo algunas llaves del diccionario
b = pd.DataFrame (usuarios, columns = ['nombre','notas'])
b

nombre  notas
0    ana     10
1  maria      1
2   flor     17
3  fanna     16

In [ ]:
#DF con matriz
#creo matriz
m = np.arange(15).reshape(3,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
df_dematriz = pd.DataFrame(m, columns = ['a','b','c','d','e'], index=['a','b','c'])
df_dematriz

a   b   c   d   e
a   0   1   2   3   4
b   5   6   7   8   9
c  10  11  12  13  14

In [ ]:
#cambiando el nombre de las columnas
df_dematriz.columns = 'A','B','C','D','E'
df_dematriz

A   B   C   D   E
a   0   1   2   3   4
b   5   6   7   8   9
c  10  11  12  13  14

In [ ]:
#cambiando el nombre de las columnas e index
print( df_dematriz.rename(columns = {'A':'1a'}) )
print( df_dematriz.rename(index = {'a':'1a'}) )


   1a   B   C   D   E
a   0   1   2   3   4
b   5   6   7   8   9
c  10  11  12  13  14
     A   B   C   D   E
1a   0   1   2   3   4
b    5   6   7   8   9
c   10  11  12  13  14


In [ ]:
a.notas[a.notas>14]

2    17
3    16
Name: notas, dtype: int64

### Ejecutar Funciones

In [ ]:
#aumentar en uno la edad de cada usuario
a.edad = a.apply( lambda row: row['edad']+1, axis=1 )#va de fila por fila
a


nombre  notas  edad  apobado
0    ana     10    15     True
1  maria     15    17     True
2   flor     17    16    False
3  fanna     16    15     True

In [ ]:
df = pd.read_csv('/content/sample_data/california_housing_test.csv', 
            delimiter=',', na_values = ['-']) #rremplazare los - por NaN
df.head()

longitude  latitude  ...  median_income  median_house_value
0    -122.05     37.37  ...         6.6085            344700.0
1    -118.30     34.26  ...         3.5990            176500.0
2    -117.81     33.78  ...         5.7934            270500.0
3    -118.36     33.82  ...         6.1359            330000.0
4    -119.67     36.33  ...         2.9375             81700.0

[5 rows x 9 columns]

In [ ]:
df.households # es de tipo float, lo voy a pasar a int

0        606.0
1        277.0
2        495.0
3         11.0
4        237.0
         ...  
2995     607.0
2996    1036.0
2997     220.0
2998      14.0
2999     260.0
Name: households, Length: 3000, dtype: float64

In [ ]:
#transformando a entero 
df.households = df.apply( lambda row: int(row['households']) , axis = 1 )
df.households

0        606
1        277
2        495
3         11
4        237
        ... 
2995     607
2996    1036
2997     220
2998      14
2999     260
Name: households, Length: 3000, dtype: int64

### Ordenando Df


In [ ]:
#ordenar por index
df.sort_index() # por default es de forma ascendnete

longitude  latitude  ...  median_income  median_house_value
0       -122.05     37.37  ...         6.6085            344700.0
1       -118.30     34.26  ...         3.5990            176500.0
2       -117.81     33.78  ...         5.7934            270500.0
3       -118.36     33.82  ...         6.1359            330000.0
4       -119.67     36.33  ...         2.9375             81700.0
...         ...       ...  ...            ...                 ...
2995    -119.86     34.42  ...         1.1790            225000.0
2996    -118.14     34.06  ...         3.3906            237200.0
2997    -119.70     36.30  ...         2.2895             62000.0
2998    -117.12     34.10  ...         3.2708            162500.0
2999    -119.63     34.42  ...         8.5608            500001.0

[3000 rows x 9 columns]

In [ ]:
#ordenar por columnas
df.sort_values('households', ascending = False) # si quiero que sea descendente

longitude  latitude  ...  median_income  median_house_value
1563    -118.44     33.98  ...         5.3359            500001.0
978     -121.53     38.48  ...         4.8811            212200.0
2014    -117.22     32.86  ...         3.6287            280800.0
1146    -117.27     33.15  ...         4.6357            244900.0
321     -121.73     37.68  ...         5.4496            238900.0
...         ...       ...  ...            ...                 ...
666     -121.89     37.42  ...         7.7197            225000.0
2494    -118.44     34.04  ...         2.1875            225000.0
740     -117.12     32.66  ...         1.1250             60000.0
2640    -114.62     33.62  ...         0.5360            275000.0
1115    -116.95     33.86  ...         1.6250             55000.0

[3000 rows x 9 columns]

### Creando archivo


In [ ]:
df.to_csv('nuevo archivo.csv', columns = ['longitude','latitude'])

### modificando DF


In [ ]:
df = pd.DataFrame(np.arange(15).reshape(3,5),
                  columns = list('abcde'),
                  index = list('abc'))
df

a   b   c   d   e
a   0   1   2   3   4
b   5   6   7   8   9
c  10  11  12  13  14

In [ ]:
#cambiando toda la columnas
df.a = 100
df

a   b   c   d   e
a  100   1   2   3   4
b  100   6   7   8   9
c  100  11  12  13  14

In [ ]:
#cambiando solo un valor
df.a[0] = 1
df

a   b   c   d   e
a    1   1   2   3   4
b  100   6   7   8   9
c  100  11  12  13  14

In [ ]:
#eliminado una columna
df.drop('c', axis = 1)

a   b   d   e
a    1   1   3   4
b  100   6   8   9
c  100  11  13  14

In [ ]:
#eliminado una fila
df.drop('b', axis = 0 )

a   b   c   d   e
a    1   1   2   3   4
c  100  11  12  13  14

In [ ]:
#agregar una columna
#si moodifica al DF
df.insert(1, 'x', [1,2,3])
df

a  x   b   c   d   e
a    1  1   1   2   3   4
b  100  2   6   7   8   9
c  100  3  11  12  13  14

In [ ]:
#agregar una columna
#genera un nuevo DF
df.assign ( z = [0,0,0])

a  x   b   c   d   e  z
a    1  1   1   2   3   4  0
b  100  2   6   7   8   9  0
c  100  3  11  12  13  14  0

### Etiquetas y posiciones en el DF

In [ ]:
dic = {
    'nombre' : ['edu','uriel', 'marines','alex'],
    'edad' : np.random.randint(15,30,4),
    'calific' : np.random.randint(0,20,4),
    'correos' : ['aqsw', 'swsed', 'aqaqs', 'eeeee']
}

data=pd.DataFrame(dic, index = list('abcd'))
data

nombre  edad  calific correos
a      edu    21       10    aqsw
b    uriel    16        7   swsed
c  marines    18       16   aqaqs
d     alex    22        2   eeeee

In [ ]:
#USando LOC Trabaja con etiquetas
data.loc['a':'c', ['nombre', 'edad']]

nombre  edad
a      edu    20
b    uriel    16
c  marines    28

In [ ]:
data.loc [ data.edad > 20 , ['nombre','edad']].sort_values('nombre')

nombre  edad
d   alex    22
a    edu    21

In [ ]:
# USando ILOC Trabaja con posiciones
data.iloc[0:2]

nombre  edad  calific correos
a    edu    21       10    aqsw
b  uriel    16        7   swsed

### Agrupando

In [ ]:
frutas = {
    'nombre' : ['naraja','manzana', 'manzana', 'pera'] ,
    'color': ['naranja','verde','verde','verde'],
    'cantidad' : np.random.randint(1,5,4)
    }
df = pd.DataFrame(frutas)
df

nombre    color  cantidad
0   naraja  naranja         3
1  manzana    verde         2
2  manzana    verde         1
3     pera    verde         2

In [ ]:
#agrupando por registros duplicados
#agrupo por nmombre y sumo la cantidad
df.groupby('nombre').cantidad.sum().to_frame('cantidad') #para que se cree un dataframe


cantidad
nombre           
manzana         3
naraja          3
pera            2

In [ ]:
#filtro los valores que agrupados son mayores que 2
df.groupby('nombre').filter( lambda fruta: fruta.cantidad.sum()>2).groupby('nombre').cantidad.sum().to_frame('cantidad')

cantidad
nombre           
manzana         3
naraja          3