<a href="https://colab.research.google.com/github/anamumaq/bootcamp-codigofacilito/blob/main/Modulo_2_Practica_Numpy_%26_Pandas_Codigofacilito.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpys
* Listas son modificables
* puedo usar dtype = np.complex si necesito usar numeros con digitos extremadamente grandes
* Para representar vacios np.nan


### Importando Numpy

In [2]:
import numpy as np

### Creando Listas

In [ ]:
lista =[1,2,3,3]

### Creando **arreglo** a traves de una lista

In [ ]:
arreglo = np.array(lista)
print(arreglo)

[1 2 3 3]


* Puedo Crear un arreglo con una lista que tenga string  y decirle que el arreglo sea de tipo int, el resultado es que convierte todos los elementos a int

In [ ]:
lista =[1,2,3,'4']
arreglo = np.array(lista, dtype = np.int)
print(arreglo)

* Puedo crear un arreglo donde todos sean string definiendo los elementos en el arreglo

In [ ]:
lista =[1,2,3,'4']
arreglo = np.array(lista, dtype = np.str)
print(arreglo)

['1' '2' '3' '4']


* Puedo crear arreglos de unos y de ceros, deficiendo dentro el tipo de elementos que quiero que sean 

In [3]:
# Creando arreglos de unos
a = np.ones(10, dtype=np.int)
print(a)

# Creando arreglos de ceros
c = np.zeros(10, dtype=np.int)
print(c)

[1 1 1 1 1 1 1 1 1 1]
[0 0 0 0 0 0 0 0 0 0]


In [4]:
print("tamano del elemento", a.size)
print("numero de dimensiones que posee el array", a.ndim)
print("la forma del array", a.shape)

tamano del elemento 10
numero de dimensiones que posee el array 1
la forma del array (10,)


### Creando arreglos con **Datos Basura**
* Devuelde elementos de cualquier tipo, normalmente puedo usarlo para definir el tamañano de un array que no se que elementos tendrá, luego puedo ir cambiando los elementos

In [ ]:
#crear arregles con datos basura
b = np.empty(10, dtype=np.int)
print(b)

[1 1 1 1 1 1 1 1 1 1]


### Creando elementos random con randint
* (inicial, final, numero de elementos)

In [ ]:
a = np.random.randint(0,20,10)

In [ ]:
#Estes el arreglo generado
a

array([ 3, 18, 14,  7, 17, 18,  5,  1,  8,  8])

### Filtrando con booleans los elementos del array

In [ ]:
# que elementos son mayores a 5 devuelve bool
a>5

array([False,  True,  True,  True,  True,  True, False, False,  True,
        True])

In [ ]:
#encuentro estos elementos mayores a 5
a[a>5]

array([18, 14,  7, 17, 18,  8,  8])

# Pandas
* Dataframe son arreglos pero con esteroides
* Pandas si usa numpys por eso es necesario primero aprender numpy

In [ ]:
#importando pandas
import pandas as pd

### Leo la bd del repo en .csv

In [ ]:
url = 'https://raw.githubusercontent.com/codigofacilito/pandas-python/master/users.csv'
df = pd.read_csv(url, index_col=0)

In [ ]:
#primeros 5 elementos de la base de datos
df.head()

nombre  edad  ...            pais                        email
0    Mr Jerome Thomas    73  ...   United States    jerome.thomas@example.com
1       Mr Gary Berry    70  ...  United Kingdom       gary.berry@example.com
2     Mr Noham Dubois    40  ...          France     noham.dubois@example.com
3   Mrs Naja Johansen    63  ...         Denmark    naja.johansen@example.com
4  Mr Damien Marchand    61  ...          France  damien.marchand@example.com

[5 rows x 5 columns]

### Aprendiendo iloc y loc

In [ ]:
 # elementos a partir de indices desde las filas
 # iloc para enteros
 # jalo la quinta fila
df.iloc[4]

nombre             Mr Damien Marchand
edad                               61
genero                           male
pais                           France
email     damien.marchand@example.com
Name: 4, dtype: object

In [ ]:
# jalando varias filas a la vez
# la segunda y tercera fila
df.iloc[[1,2]]

nombre  edad genero            pais                     email
1    Mr Gary Berry    70   male  United Kingdom    gary.berry@example.com
2  Mr Noham Dubois    40   male          France  noham.dubois@example.com

In [ ]:
#Loc para strings
df.loc[:,'edad']

0      73
1      70
2      40
3      63
4      61
       ..
195    46
196    40
197    40
198    37
199    60
Name: edad, Length: 200, dtype: int64

### Extraigo los NaN

In [ ]:
#quitando NaN
data = df.dropna()

In [ ]:
data.info

<bound method DataFrame.info of                  nombre  edad  ...            pais                        email
0      Mr Jerome Thomas    73  ...   United States    jerome.thomas@example.com
1         Mr Gary Berry    70  ...  United Kingdom       gary.berry@example.com
2       Mr Noham Dubois    40  ...          France     noham.dubois@example.com
3     Mrs Naja Johansen    63  ...         Denmark    naja.johansen@example.com
4    Mr Damien Marchand    61  ...          France  damien.marchand@example.com
..                  ...   ...  ...             ...                          ...
195       Mr Raul Bravo    46  ...           Spain       raul.bravo@example.com
196   Miss Maeva Fortin    40  ...          Canada     maeva.fortin@example.com
197   Mr Gabriel Berger    40  ...          France   gabriel.berger@example.com
198  Mrs Ülkü Tanrıkulu    37  ...          Turkey   ulku.tanrikulu@example.com
199     Mr Raff Valkema    60  ...     Netherlands     raff.valkema@example.com

[200 ro

## Obteniendo informacion de un dataframe

### Obtener el nombre de todos los usuarios que edad sean mayor a 40

In [ ]:
#usuarios con edad mayor a 40
data[data['edad']>40]

nombre  edad  ...            pais                         email
0       Mr Jerome Thomas    73  ...   United States     jerome.thomas@example.com
1          Mr Gary Berry    70  ...  United Kingdom        gary.berry@example.com
3      Mrs Naja Johansen    63  ...         Denmark     naja.johansen@example.com
4     Mr Damien Marchand    61  ...          France   damien.marchand@example.com
5       Mr Harri Althoff    56  ...         Germany     harri.althoff@example.com
..                   ...   ...  ...             ...                           ...
191        Mr Noah Moore    44  ...     New Zealand        noah.moore@example.com
193  Ms Delphine Ginnish    58  ...          Canada  delphine.ginnish@example.com
194  Madame Rosa Lefevre    67  ...     Switzerland      rosa.lefevre@example.com
195        Mr Raul Bravo    46  ...           Spain        raul.bravo@example.com
199      Mr Raff Valkema    60  ...     Netherlands      raff.valkema@example.com

[122 rows x 5 columns]

In [ ]:
# Nombre de los usuarios con edad mayor a 40
data[data['edad']>40]['nombre']

0         Mr Jerome Thomas
1            Mr Gary Berry
3        Mrs Naja Johansen
4       Mr Damien Marchand
5         Mr Harri Althoff
              ...         
191          Mr Noah Moore
193    Ms Delphine Ginnish
194    Madame Rosa Lefevre
195          Mr Raul Bravo
199        Mr Raff Valkema
Name: nombre, Length: 122, dtype: object

### Obtener el nombre de todos los usuarios que edad sean mayor a 40 y de sexo *femenino*

In [ ]:
data[(data['edad'] > 40) & (data['genero'] =='female')]['nombre']

3            Mrs Naja Johansen
9         Miss Emilia Laitinen
10         Ms Cathriona Hanson
11            Miss Maia Clarke
12           Ms Cathy Simmmons
                ...           
181             Mrs Avery King
182            Mrs Soila Silva
190    Miss Margrietha Holster
193        Ms Delphine Ginnish
194        Madame Rosa Lefevre
Name: nombre, Length: 68, dtype: object

### Probando strings
* Puedo usar **.str.endwith** para extraer los textos que temrinen con determinada caracteristica

In [ ]:
# que terminen con example

data[data['email'].str.endswith('@example.com')] 

nombre  edad  ...            pais                        email
0      Mr Jerome Thomas    73  ...   United States    jerome.thomas@example.com
1         Mr Gary Berry    70  ...  United Kingdom       gary.berry@example.com
2       Mr Noham Dubois    40  ...          France     noham.dubois@example.com
3     Mrs Naja Johansen    63  ...         Denmark    naja.johansen@example.com
4    Mr Damien Marchand    61  ...          France  damien.marchand@example.com
..                  ...   ...  ...             ...                          ...
195       Mr Raul Bravo    46  ...           Spain       raul.bravo@example.com
196   Miss Maeva Fortin    40  ...          Canada     maeva.fortin@example.com
197   Mr Gabriel Berger    40  ...          France   gabriel.berger@example.com
198  Mrs Ülkü Tanrıkulu    37  ...          Turkey   ulku.tanrikulu@example.com
199     Mr Raff Valkema    60  ...     Netherlands     raff.valkema@example.com

[199 rows x 5 columns]

In [ ]:
# que NO terminen con example

data[~data['email'].str.endswith('@example.com')] 

nombre  edad genero    pais                 email
151  Mr Thomas Lam    42   male  Canada  thomas.lam@gmail.com

### Obtener los paises de Germany, Finland y Canada

In [ ]:
data[(data['pais'] == 'Germany')|(data['pais'] == 'Finland')|(data['pais'] == 'Canada')]

nombre  edad  ...     pais                            email
5          Mr Harri Althoff    56  ...  Germany        harri.althoff@example.com
7         Ms Britta Weinert    35  ...  Germany       britta.weinert@example.com
9      Miss Emilia Laitinen    53  ...  Finland      emilia.laitinen@example.com
20     Mr Vincenzo Rauscher    25  ...  Germany    vincenzo.rauscher@example.com
21            Mr Louis Ross    60  ...   Canada           louis.ross@example.com
31          Mr Toivo Kotila    27  ...  Finland         toivo.kotila@example.com
36          Mr Anthony Wong    42  ...   Canada         anthony.wong@example.com
38        Mrs Lotta Rintala    26  ...  Finland        lotta.rintala@example.com
41         Miss Iida Ketola    46  ...  Finland          iida.ketola@example.com
45        Ms Ilona Moilanen    22  ...  Finland       ilona.moilanen@example.com
47         Miss Ellen Rinne    66  ...  Finland          ellen.rinne@example.com
50           Mr Theo Miller    33  ...   Canada          theo.miller@example.com
53          Ms Aino Lassila    54  ...  Finland         aino.lassila@example.com
56       Ms Marcella Brosch    38  ...  Germany      marcella.brosch@example.com
58       Miss Madison Ennis    49  ...   Canada        madison.ennis@example.com
72           Ms Megan Brown    26  ...   Canada          megan.brown@example.com
79   Ms Hanne Aschenbrenner    64  ...  Germany  hanne.aschenbrenner@example.com
85       Mrs Luisa Weißmann    32  ...  Germany      luisa.weissmann@example.com
87         Mr Joona Koskela    59  ...  Finland        joona.koskela@example.com
88            Mrs Hilda Epp    22  ...  Germany            hilda.epp@example.com
131          Mr Xavier Addy    30  ...   Canada          xavier.addy@example.com
133      Miss Julia Ambrose    34  ...   Canada        julia.ambrose@example.com
144        Ms Mareile Plate    51  ...  Germany        mareile.plate@example.com
147         Mr Lauri Kotila    32  ...  Finland         lauri.kotila@example.com
151           Mr Thomas Lam    42  ...   Canada             thomas.lam@gmail.com
158   Mr Rafael Spangenberg    33  ...  Germany   rafael.spangenberg@example.com
170           Mr Ryder Côté    25  ...   Canada           ryder.cote@example.com
174       Ms Isla Koistinen    37  ...  Finland       isla.koistinen@example.com
184      Mr Philip Bélanger    24  ...   Canada      philip.belanger@example.com
193     Ms Delphine Ginnish    58  ...   Canada     delphine.ginnish@example.com
196       Miss Maeva Fortin    40  ...   Canada         maeva.fortin@example.com

[31 rows x 5 columns]

In [ ]:
# otra forma de hacer varios filtros en uno solo
data[(data['pais'].isin ( ['Germany','Finland']))]

nombre  edad  ...     pais                            email
5          Mr Harri Althoff    56  ...  Germany        harri.althoff@example.com
7         Ms Britta Weinert    35  ...  Germany       britta.weinert@example.com
9      Miss Emilia Laitinen    53  ...  Finland      emilia.laitinen@example.com
20     Mr Vincenzo Rauscher    25  ...  Germany    vincenzo.rauscher@example.com
31          Mr Toivo Kotila    27  ...  Finland         toivo.kotila@example.com
38        Mrs Lotta Rintala    26  ...  Finland        lotta.rintala@example.com
41         Miss Iida Ketola    46  ...  Finland          iida.ketola@example.com
45        Ms Ilona Moilanen    22  ...  Finland       ilona.moilanen@example.com
47         Miss Ellen Rinne    66  ...  Finland          ellen.rinne@example.com
53          Ms Aino Lassila    54  ...  Finland         aino.lassila@example.com
56       Ms Marcella Brosch    38  ...  Germany      marcella.brosch@example.com
79   Ms Hanne Aschenbrenner    64  ...  Germany  hanne.aschenbrenner@example.com
85       Mrs Luisa Weißmann    32  ...  Germany      luisa.weissmann@example.com
87         Mr Joona Koskela    59  ...  Finland        joona.koskela@example.com
88            Mrs Hilda Epp    22  ...  Germany            hilda.epp@example.com
144        Ms Mareile Plate    51  ...  Germany        mareile.plate@example.com
147         Mr Lauri Kotila    32  ...  Finland         lauri.kotila@example.com
158   Mr Rafael Spangenberg    33  ...  Germany   rafael.spangenberg@example.com
174       Ms Isla Koistinen    37  ...  Finland       isla.koistinen@example.com

[19 rows x 5 columns]

### Obtener los mujeres que sean de Germany

In [ ]:
# Filtrando mujeres de alemania
data[(data['genero']=='female') & (data['pais']=='Germany')]

nombre  edad  ...     pais                            email
7         Ms Britta Weinert    35  ...  Germany       britta.weinert@example.com
56       Ms Marcella Brosch    38  ...  Germany      marcella.brosch@example.com
79   Ms Hanne Aschenbrenner    64  ...  Germany  hanne.aschenbrenner@example.com
85       Mrs Luisa Weißmann    32  ...  Germany      luisa.weissmann@example.com
88            Mrs Hilda Epp    22  ...  Germany            hilda.epp@example.com
144        Ms Mareile Plate    51  ...  Germany        mareile.plate@example.com

[6 rows x 5 columns]

### Cuantos hombres hay en Canada

In [ ]:
# cuenta el resultado del filtro en cada fila
data[(data['genero']=='male') & (data['pais']=='Canada')].count()

nombre    7
edad      7
genero    7
pais      7
email     7
dtype: int64

In [ ]:
# Cuenta el resultado del filtro solo del pais
data[(data['genero']=='male') & (data['pais']=='Canada')]['pais'].count()

7

## Groupby

## Cuantos hombre y mujeres hay en toda la tabla

In [ ]:
data.groupby('genero').count()

nombre  edad  pais  email
genero                           
female     106   106   106    106
male        94    94    94     94

In [ ]:
data.groupby('genero').count().index.values # obtengo el arreglo

array(['female', 'male'], dtype=object)

In [ ]:
data.groupby('genero')['genero'].count()

genero
female    106
male       94
Name: genero, dtype: int64

### Encontrar el pais con mas mujeres
* Filtra mujeres
* Agrupa segun pais los ya filtrado
* Cuenta solos elementos de pais

In [ ]:
# el pais con mas mujeres
data[data['genero']=='female'].groupby('pais')['pais'].count()

pais
Australia          6
Brazil             5
Canada             5
Denmark           12
Finland            7
France             4
Germany            6
Iran               5
Ireland            6
Netherlands        4
New Zealand       10
Norway             6
Spain              9
Switzerland        6
Turkey             7
United Kingdom     6
United States      2
Name: pais, dtype: int64

* Ordena la tabla agrupada por pais de manera descentende
* Solo me importa tener el primer encabezado

In [ ]:
data[data['genero']=='female'].groupby('pais')['pais'].count().sort_values(ascending=False).head(1)

pais
Denmark    12
Name: pais, dtype: int64

### Obtener el pais con menos usuarios

In [ ]:
data.groupby('pais')['pais'].count().sort_values()

pais
Netherlands        6
Brazil             9
Switzerland        9
Germany            9
United States     10
Finland           10
France            10
Turkey            12
Australia         12
Canada            12
Iran              13
Spain             13
New Zealand       14
Norway            14
United Kingdom    15
Denmark           16
Ireland           16
Name: pais, dtype: int64